version: '3'
services:
  gateway: 
    image: pkoperek/cloudsimplus-gateway:latest
  
  manager:
    image: pkoperek/dqn-manager:latest
    build: 
      context: .
    depends_on:
      - gateway
    environment:
      - CLOUDSIM_GATEWAY_HOST=gateway
      - TEST_CASE=dcnull
    command: ./wait-for gateway:25333 -- python test_model.py
