version: '3'
services:
  gateway: 
    image: pkoperek/cloudsimplus-gateway:latest
    environment:
      - TEST_FILE=KTH-SP2-1996-2.1-cln_50.swf
    ports:
      - 25333:25333
  
  manager:
    image: pkoperek/dqn-manager:latest
    build: 
      context: .
    depends_on:
      - gateway
    environment:
      - CLOUDSIM_GATEWAY_HOST=gateway
      - TEST_CASE=model
      - BATCH_SIZE=4
        #- TEST_CASE=run

    command: ./wait-for gateway:25333 -- python test_model.py
    volumes:
      - ./model-storage:/storage
