version: '3'
services:
  gateway: 
    image: cloudsimplus-gateway:latest
  
  manager:
    image: dqn-manager:latest
    build: 
      context: .
    depends_on:
      - gateway
    environment:
      - CLOUDSIM_GATEWAY_HOST=gateway
    command: ./wait-for gateway:25333 -- python test_model.py
