apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqn-manager-deployment
  labels:
    app: dqn-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dqn-manager
  template:
    metadata:
      labels:
        app: dqn-manager
    spec:
      containers:
      - name: manager
        image: pkoperek/dqnmanager:latest
        imagePullPolicy: Always

---
kind: Service
apiVersion: apps/v1
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 25333
    targetPort: 25333

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: pkoperek/cloudsimplusgateway
        image: cloudsimplusgateway:latest
