apiVersion: batch/v1
kind: Job
metadata:
  name: dqn-manager-job
spec:
  template:
    spec:
      containers:
      - name: manager
        image: pkoperek/dqn-manager:latest
        imagePullPolicy: Always
        env:
        - name: CLOUDSIM_GATEWAY_HOST
          value: gateway-service
        - name: TEST_CASE
          value: model
      restartPolicy: Never

---
kind: Service
apiVersion: v1
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 25333
    targetPort: 25333

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: cloudsimplus-gateway
        image: pkoperek/cloudsimplus-gateway:latest
        imagePullPolicy: Always
